// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqrvppyckxcumzcgoogd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxcnZwcHlja3hjdW16Y2dvb2dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1ODA5NjQsImV4cCI6MjA1MDE1Njk2NH0.Q2CvAgRCPj-OABIRF3aY8UQog7SzstKJX1w4kaCyoac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);